apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: web
        image: api
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"     
        ports:
        - containerPort: 8080
          name: gunicorn